- name: Install basic packages for system
  apt: name={{item}} state=latest
  with_items:
    - vim
    - python-software-properties
    - htop
    - sysv-rc-conf
    - python-pycurl
  tags: install_basic_packages
