---
#http://docs.ansible.com/digital_ocean_module.html
#https://github.com/elbuo8/blogs/tree/master/Ansible%20%26%20DigitalOcean
#http://sendgrid.com/blog/ansible-and-digital-ocean/
#https://github.com/garethr/ansible-provisioner
- hosts: localhost
  #connection: local
  gather_facts: False
  tasks:
    - name: Create a new DO Droplet
      digital_ocean: >
        state=present
        command=droplet
        client_id={{ do_client_id }}
        api_key={{ do_api_key }}
        ssh_key_ids={{ do_ssh_key_ids }}
        name={{ do_name }}
        size_id={{ do_size }}
        region_id={{ do_region }}
        image_id={{ do_image }}
        wait_timeout=500
        wait=yes
        virtio=yes
      register: my_droplet
    - debug: msg="ID is {{ my_droplet.droplet.id }}"
    - debug: msg="IP is {{ my_droplet.droplet.ip_address }}"