- name: Install rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest={{deploy_user_home}}/.rbenv
  tags: install_rbenv

- name: Setting Rbenv Environment
  script: rbenv.sh
  tags: setting_rbenv

- name: Install rbenv plugin - ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git dest={{deploy_user_home}}/.rbenv/plugins/ruby-build
  tags: install_ruby_build

- name: Install rbenv plugin - rbenv-rehash
  git: repo=git://github.com/sstephenson/rbenv-gem-rehash.git dest={{deploy_user_home}}/.rbenv/plugins/rbenv-rehash
  tags: install_rbenv_rehash

- name: Install rbenv plugin - rbenv-update
  git: repo=git://github.com/rkh/rbenv-update.git dest={{deploy_user_home}}/.rbenv/plugins/rbenv-update
  tags: install_rbenv_update

- name: Install rbenv plugin - rbenv default rbenv-gem
  git: repo=git://github.com/sstephenson/rbenv-default-gems.git dest={{deploy_user_home}}/.rbenv/plugins/rbenv-default-gems
  tags: install_rbenv_default_gems

- name: Generate file rbenv default gems
  shell: echo 'bundler' > {{deploy_user_home}}/.rbenv/default-gems
  tags: setting_default_gems
